# Stage 1: Build stage to install dependencies
FROM public.ecr.aws/lambda/python:3.11 as build

# Install build-time dependencies
RUN yum update && yum install -y gcc

# Create a virtual environment
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

# Copy requirements files
WORKDIR /app
COPY requirements.txt requirements-lambda.txt ./

# Install dependencies into the virtual environment
# This caches the installed packages in this layer
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-lambda.txt


# Stage 2: Final stage for the Lambda image
FROM public.ecr.aws/lambda/python:3.11

# Copy the virtual environment from the build stage
COPY --from=build /venv /venv

# Set the path to include the virtual environment
ENV PATH="/venv/bin:$PATH"
ENV PYTHONPATH="/venv/lib/python3.11/site-packages"

# Copy the application code
WORKDIR /var/task
COPY ./app ./app
COPY lambda_handler.py .

# Set the command to run the handler
# The format is <file_name>.<handler_function_name>
CMD [ "lambda_handler.handler" ]